# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a24a99e8079e182061849fba63089abf6c5f9423c6c52eb28f3daf13b7626dfa97ba4727285478a546cd7242bf6d4c86aba8626d3f7511102d125f13616cc624

test:
  secret_key_base: 4c70e00f297e2acee63993aa0c1966acd0a648ea01097c109f8d7073a7e77aaa0241a3c8a0746f291897375114f256ee25bae9dc5c07184319da00855287b9ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
